### ISSUE TITLE
Miejska Dżungla

### ISSUE THREAD

**Issue by KrzyzanTTV** [polskie-mapy/data#10]
### Nazwa punktu

Sprawa dla reportera - Miejska Dżungla

### Lokalizacja zdarzenia

Dzielnica "Nowy Świat" Siemianowice Śląskie

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=nq7ND1OUS9I

### Dlaczego ten punkt powinien znaleźć się na mapie?

Ponieważ wiele z fragmentów tego materiału stało się viralem w Polskim Internecie jak np. "psy kupy jedzą" czy "Oczu Pan nie ma, Gałek ocznych prawda? Pobili mnie!"

**Comment by KrzyzanTTV** [comment]
Dokładna lokalizacja
https://goo.gl/maps/2diiqkd7SFMXcchk9

**Comment by RonaldinhoTHC** [comment]
myślę, że do sprawy dla reportera będzie osobna mapka ;)
