### ISSUE TITLE
Hitler nie wiedział o holokauście

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#101]
### Nazwa punktu

Adolf H*tler nie wiedział o holokauście

### Lokalizacja zdarzenia

52°13'13.4"N 21°02'08.5"E

### Linki do zdarzenia / filmu

https://youtu.be/GxW_m6doKww

### Dlaczego ten punkt powinien znaleźć się na mapie?

Chyba nie muszę tłumaczyć

**Comment by RonaldinhoTHC** [comment]
dodałem
