### ISSUE TITLE
Wypadek księdza podczas mszy w Skawinie

### ISSUE THREAD

**Issue by KyleBzPL** [polskie-mapy/data#102]
### Nazwa punktu

"Pan jezus już się zbliża" Wypadek księdza podczas mszy w Skawinie

### Lokalizacja zdarzenia

49°58'09.4"N 19°50'05.5"E

### Linki do zdarzenia / filmu

https://www.youtube.com/shorts/aRuDYbST_lc?feature=share

### Proponowana ikona

https://fontawesome.com/icons/person-falling?f=classic&s=solid

### Proponowany kolor

#4287f5

### Dlaczego ten punkt powinien znaleźć się na mapie?

Według mnie coś takiego powinno się znaleźć na mapie, pozdrawiam serdecznie.

**Comment by RonaldinhoTHC** [comment]
dodałem

**Comment by KyleBzPL** [comment]
klikam i nie działa coś ale jest

**Comment by cvgore** [comment]
poprawione, teraz powinno działać ;)
https://mapainternetow.pl/maps/1/point/518
