### ISSUE TITLE
może na grzybach są

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#103]
### Nazwa punktu

może na grzybach są

### Lokalizacja zdarzenia

54°02'41.6"N 18°42'14.3"E

### Linki do zdarzenia / filmu

https://youtu.be/NUgkxfIDZGo

### Dlaczego ten punkt powinien znaleźć się na mapie?

Dość memiczna sonda wśród mieszkańców wioski z 3,5mln wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodalem
