### ISSUE TITLE
sprzedawca kukurydzy

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#106]
### Nazwa punktu

sprzedawca kukurydzy

### Lokalizacja zdarzenia

plaża, Mielno, powiat koszaliński

### Linki do zdarzenia / filmu

https://www.youtube.com/shorts/qlMLaLJS46M

### Dlaczego ten punkt powinien znaleźć się na mapie?

400k ludzi zobaczyło jak ksiądz dorabia w wakacje

**Comment by RonaldinhoTHC** [comment]
dodalem
