### ISSUE TITLE
KOBEX-WYLICZANKA

### ISSUE THREAD

**Issue by kszyman** [polskie-mapy/data#107]
### Nazwa punktu

KOBEX-WYLICZANKA

### Lokalizacja zdarzenia

53°02'01.7"N 16°26'44.0"E

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=b4TKmjhOTrY

### Dlaczego ten punkt powinien znaleźć się na mapie?

Uważam,że jest to filmik, który można nazwać hitem internetu i umieścić na mapie

**Comment by H0RNY-DR4G0N** [comment]
Nie osiąga progu wyświetleń
