### ISSUE TITLE
Bóbr kurwa

### ISSUE THREAD

**Issue by wankerino** [polskie-mapy/data#109]
### Nazwa punktu

Bóbr kurwa

### Lokalizacja zdarzenia

50°58'24.5"N 16°14'04.4"E

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=OHHpYXQyQO4

### Proponowany kolor

#3b2c07

### Dlaczego ten punkt powinien znaleźć się na mapie?

ja pierdolę jakie bydle - BOBER

**Comment by RonaldinhoTHC** [comment]
dodalem
