### ISSUE TITLE
Wkurzona babcia wyzywa policjanta

### ISSUE THREAD

**Issue by KrzyzanTTV** [polskie-mapy/data#11]
### Nazwa punktu

Wkurzona babcia wyzywa policjanta

### Lokalizacja zdarzenia

Krupanka 93 Siemianowice Śląskie (zatoczka autobusowa)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=UgGEWG-TVyQ

### Dlaczego ten punkt powinien znaleźć się na mapie?

Spora ilość wyświetleń, wiele cytatów z tego video było potem viralowo powtarzane jak np. "Czego się kurwa przypierdalasz?!"

**Comment by RonaldinhoTHC** [comment]
dodane
