### ISSUE TITLE
Ksiądz zapytał dzieci, kto pójdzie do piekła.

### ISSUE THREAD

**Issue by kszyman** [polskie-mapy/data#110]
### Nazwa punktu

Kto pójdzie do piekła?

### Lokalizacja zdarzenia

https://www.google.com/maps/place/Ko%C5%9Bci%C3%B3%C5%82+%C5%9Awi%C4%99tej+Tr%C3%B3jcy+w+Poznaniu/@52.369384,16.9028868,35m/data=!3m1!1e3!4m6!3m5!1s0x47045ac6059c3615:0x92728256f9049514!8m2!3d52.369402!4d16.9030529!16s%2Fg%2F120xv5jz?entry=ttu

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=2ReMf5SZqXg

### Dlaczego ten punkt powinien znaleźć się na mapie?

Ponad pół miliona wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodalem
