### ISSUE TITLE
Cud w Parczewie

### ISSUE THREAD

**Issue by kszyman** [polskie-mapy/data#111]
### Nazwa punktu

Cud w Parczewie

### Lokalizacja zdarzenia

https://www.google.com/maps/place/Miejsce+objawienia+Matki+Boskiej/@51.640998,22.9067648,113m/data=!3m1!1e3!4m6!3m5!1s0x472231f4b4328161:0xa411ada5bfd5779d!8m2!3d51.641102!4d22.9067971!16s%2Fg%2F11v03ng_m5?entry=ttu

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=NagknPhnaYc

### Proponowana ikona

https://fontawesome.com/icons/tree?f=classic&s=solid

### Dlaczego ten punkt powinien znaleźć się na mapie?

Milion wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodalem
