### ISSUE TITLE
Libacja na skwerku

### ISSUE THREAD

**Issue by Tymekin** [polskie-mapy/data#113]
### Nazwa punktu

Libacja na skwerku

### Lokalizacja zdarzenia

Wrocław, ul. Ciepła 15

### Linki do zdarzenia / filmu

https://gazetawroclawska.pl/wroclaw-libacja-na-skwerku/ar/297518
https://pl.wikipedia.org/wiki/Wroc%C5%82aw:_Libacja_na_skwerku

### Proponowana ikona

people-group

### Proponowany kolor

#abf24e

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jeden z najbardziej znanych artykułów prasowych, a zarazem jeden z najbardziej groteskowych.

**Comment by RonaldinhoTHC** [comment]
brak filmiku
