### ISSUE TITLE
Rozjebane ruskie gówno 

### ISSUE THREAD

**Issue by MasterPrecel** [polskie-mapy/data#115]
### Nazwa punktu

Rozjebane ruskie gówno 

### Lokalizacja zdarzenia

Vokzal'na St, 28, Bucha, Kyivs'ka oblast, Ukraine, 08292

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=IOVlrZSxIII&t=38s

### Proponowana ikona

person-military-rifle

### Dlaczego ten punkt powinien znaleźć się na mapie?

25% Polak opowiada jak walczy z Rosjanami. Pozdrawia Artura i szanowne polskie państwo. Ta wersja ma mało wyświetleń bo jest całością tego nagrania, inne wycinki są bardziej znane.

**Comment by H0RNY-DR4G0N** [comment]
Podałbyś film z co najmniej 100k viewsów, bo inaczej się nie dostanie
