### ISSUE TITLE
DPD wali boka 

### ISSUE THREAD

**Issue by MasterPrecel** [polskie-mapy/data#116]
### Nazwa punktu

DPD wali boka 

### Lokalizacja zdarzenia

Bielsko-BIała skrzyżowanie ulicy Karpackiej i Partyzantów, dokładna lokalizacja: 49.808093352114476, 19.042586036386126

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=L0Sd7OZPDf8

### Proponowana ikona

truck

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jest to zdarzenie niecodzienne.

**Comment by H0RNY-DR4G0N** [comment]
Żałosna ilość wyświetleń; Nie ma bata, że się dostanie
