### ISSUE TITLE
A powiedz bondziorno

### ISSUE THREAD

**Issue by Galli17** [polskie-mapy/data#129]
### Nazwa punktu

Bondziorno 

### Lokalizacja zdarzenia

Tychowo 78-220

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=dfqn8U-QzGc&ab_channel=kamiltychowo1

### Proponowana ikona

 .

### Proponowany kolor

 .

### Dlaczego ten punkt powinien znaleźć się na mapie?

 .

**Comment by H0RNY-DR4G0N** [comment]
O wiele za niskie wymagania
