### ISSUE TITLE
CO DOPALACZE ROBIA ROBIA Z LUDZMI...

### ISSUE THREAD

**Issue by Grosik212** [polskie-mapy/data#130]
### Nazwa punktu

CO DOPALACZE ROBIA ROBIA Z LUDZMI...

### Lokalizacja zdarzenia

Radomska 15, 27-200 Starachowice

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=QEdrskKEAuw

### Dlaczego ten punkt powinien znaleźć się na mapie?

Znany film w internecie z mało znanego miasta :)

**Comment by H0RNY-DR4G0N** [comment]
Znany film
86k wyświetleń
Wybierz jedno

**Comment by RonaldinhoTHC** [comment]
nie ma potrzeby komentować @H0RNY-DR4G0N
