### ISSUE TITLE
Legendarny mem z radia maryja

### ISSUE THREAD

**Issue by NotFazi** [polskie-mapy/data#14]
### Nazwa punktu

Legendarny mem z radia maryja

### Lokalizacja zdarzenia

ul, Żwirki i Wigury 80, Toruń

### Linki do zdarzenia / filmu

https://youtu.be/iRPsOk1gvgA

### Proponowana ikona

https://fontawesome.com/icons/cross?f=classic&s=solid

### Proponowany kolor

#0a26fc

### Dlaczego ten punkt powinien znaleźć się na mapie?

Dzwoni słuchacz radia tam i mówi ch*j ci w dupe

**Comment by NotFazi** [comment]
zaakecptujesz?

**Comment by RonaldinhoTHC** [comment]
zaakcepuje ;-)
