### ISSUE TITLE
Sławomir miłość w zakopanym na budowie

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#15]
### Nazwa punktu

Sławomir miłość w zakopanym na budowie

### Lokalizacja zdarzenia

Zawadzkie, ul. Powstańców Śląskich 17 (50.6060579,18.4848447)

### Linki do zdarzenia / filmu

https://youtu.be/sRrihsQPwYo

### Dlaczego ten punkt powinien znaleźć się na mapie?

Ponad 14 milionów wyświetleń mówi samo za siebie.

**Comment by RonaldinhoTHC** [comment]
no niech ci będzie... nie popieram tego ale dodam żeby nie było
