### ISSUE TITLE
Taksówka ugrzęzła na rondzie w Rypinie

### ISSUE THREAD

**Issue by szczotkadokibla** [polskie-mapy/data#150]
### Nazwa punktu

Taksówka ugrzęzła na rondzie w Rypinie

### Lokalizacja zdarzenia

Rypin

### Linki do zdarzenia / filmu

https://youtu.be/GfpQx4Tgwmg
https://cdn.wiocha.pl/webps/c/f/cfe1bb439b7df7b538b29ea959692d6b.webp

### Dlaczego ten punkt powinien znaleźć się na mapie?

Zdjęcie swego czasu obiegło internet, tak jak i nagranie słabej jakości (wiem, mało wyświetleń, zdjęcie było popularniejsze), pewnie jeszcze kręcone telefonem z Symbianem.

**Comment by RonaldinhoTHC** [comment]
fajne śmieszne ale mamy taką zasade że memy obrazkowe nie wchodzą na naszą mapke
