### ISSUE TITLE
Miś z Krupówek

### ISSUE THREAD

**Issue by szczotkadokibla** [polskie-mapy/data#151]
### Nazwa punktu

Miś z Krupówek

### Lokalizacja zdarzenia

Zakopane, Krupówki

### Linki do zdarzenia / filmu

https://www.youtube.com/shorts/iL8hdfv1pFY?feature=share

### Dlaczego ten punkt powinien znaleźć się na mapie?

Był to bardzo duży hit internetu, nawet osoby e-wykluczone o tym zdarzeniu słyszały, więc według mnie powinno się to znaleźć na tej mapie. Słynna akcja, kiedy aktorka chciała nagrać rolkę i miś się wepchnął kadr i żądał zapłaty.

**Comment by RonaldinhoTHC** [comment]
za nowe na ten moment mało wyświetleń do tego
