### ISSUE TITLE
Pale i sram - nowy punkt

### ISSUE THREAD

**Issue by hidden0bi** [polskie-mapy/data#154]
### Nazwa punktu

Pale i sram

### Lokalizacja zdarzenia

Brodnica, park (nie wiem który)

### Linki do zdarzenia / filmu

Link do youtube
https://www.youtube.com/watch?v=TBJz9tJtOvA

### Proponowana ikona

https://fontawesome.com/icons/poop?f=classic&s=solid

### Proponowany kolor

#6e3700

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jest to kawałek polskiej kultury. Bardzo ważne miejsce dla każdego Brodniczanina. Pozdrawiam ~ x1ndyk

**Comment by RonaldinhoTHC** [comment]
było już na mapce ale spadło z YT i nie ma dobrych uploadów
