### ISSUE TITLE
MÓJ PASSAT ROBI WE WSI SZUM

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#155]
### Nazwa punktu

MÓJ PASSAT ROBI WE WSI SZUM

### Lokalizacja zdarzenia

Cedzyna (50.868420, 20.731440)

### Linki do zdarzenia / filmu

https://youtu.be/RK_ZkwXIO2s?t=61

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jedna z pamiętnych parodii znanych piosenek.

**Comment by RonaldinhoTHC** [comment]
dodałem
