### ISSUE TITLE
Walka Żuli KUMITSU żmija zabija nieboszczyka

### ISSUE THREAD

**Issue by Barmtoszek** [polskie-mapy/data#158]
### Nazwa punktu

Walka Żuli KUMITSU

### Lokalizacja zdarzenia

Rzuców (51.28762551282079, 20.73466795475767)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=h87YawaGMQY

### Dlaczego ten punkt powinien znaleźć się na mapie?

13 lat temu, 676tys. wyświetleń 
teksty typu "KUMITSU" "żmija zabija nieboszczyka"

**Comment by RonaldinhoTHC** [comment]
film usunięty przez Lorda YT
