### ISSUE TITLE
Zawadzka: 6 stycznia dokonałam aborcji

### ISSUE THREAD

**Issue by janeklatlas** [polskie-mapy/data#159]
### Nazwa punktu

6 stycznia dokonałam aborcji

### Lokalizacja zdarzenia

52°14'27.9"N 21°00'59.4"E

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=_3ijz7VL5Io

### Proponowany kolor

#ED32ED

### Dlaczego ten punkt powinien znaleźć się na mapie?

Nagranie swego czasu bardzo popularne, pojawiało sie w filmach wielu twórców np. SerafinTV

**Comment by RonaldinhoTHC** [comment]
dodałem
