### ISSUE TITLE
Policja Pyta

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#160]
### Nazwa punktu

Policja Pyta

### Lokalizacja zdarzenia

E.Leclerc, ul. Żeromskiego, Elbląg (54.153417, 19.420528)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=zjlHPF4gkcE

### Dlaczego ten punkt powinien znaleźć się na mapie?

4,8 mln wyświetleń.

**Comment by RonaldinhoTHC** [comment]
dodałem
