### ISSUE TITLE
Otwarcie 2000 Biedronki

### ISSUE THREAD

**Issue by janeklatlas** [polskie-mapy/data#162]
### Nazwa punktu

Otwarcie 2000 Biedronki - tłumy rzucają się na hostessy!

### Lokalizacja zdarzenia

Łódź ul. Rokicińska 366 (51°44'32.8"N 19°36'35.7"E)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=RGuwUBnu20g

### Proponowana ikona

https://fontawesome.com/icons/shop?f=classic&s=solid

### Proponowany kolor

#F54E00

### Dlaczego ten punkt powinien znaleźć się na mapie?

Najbardziej znany film obrazujący polskie zbiorowe cebulactwo

**Comment by RonaldinhoTHC** [comment]
dodałem
