### ISSUE TITLE
Lidl walka o Crocs-y

### ISSUE THREAD

**Issue by janeklatlas** [polskie-mapy/data#163]
### Nazwa punktu

Lidl walka o Crocs-y

### Lokalizacja zdarzenia

Latchorzew 52°14'45.7"N 20°51'15.7"E

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=ptsTG_Iu3zg

### Proponowana ikona

https://fontawesome.com/icons/shoe-prints?f=classic&s=solid

### Proponowany kolor

#0049F5

### Dlaczego ten punkt powinien znaleźć się na mapie?

Kultowe nagranie z serii janusze w akcji, 2 mln wyswietleń

**Comment by RonaldinhoTHC** [comment]
dodałem!!!!!!!! LEGENDA!!!!!!!!!!!!
