### ISSUE TITLE
Wybuch bomby w Żaganiu

### ISSUE THREAD

**Issue by vvISDvv** [polskie-mapy/data#165]
### Nazwa punktu

WYBUCH bomby ZAGAN 2013 DETONACJA 500 KG MATERIALU

### Lokalizacja zdarzenia

okolice miasta Żagań 

### Linki do zdarzenia / filmu

https://youtu.be/VLA3_1W60Vk?si=yU7O0xe_d8euGY2M

### Dlaczego ten punkt powinien znaleźć się na mapie?

jebudu z udziałem kolesia przypominającego Stonogę

**Comment by RonaldinhoTHC** [comment]
dodałem
