### ISSUE TITLE
Wyścig po darmowe zakupy w Lidlu(Koszalin)

### ISSUE THREAD

**Issue by RossRabiaka** [polskie-mapy/data#167]
### Nazwa punktu

Wyścig po darmowe zakupy w Lidlu

### Lokalizacja zdarzenia

Lidl w którym odbył się wyścig, znajduje się w Koszalinie, na ulicy Śniadeckich 10( informacje o lokalizacji są w artykule z gk24) 

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=h-oZTf04AhU

Przysyłam też link do artykułu, w którym podana jest nazwa ulicy, lidl na tej ulicy jest tylko jeden, stąd maksimum pewności, że to ten.

https://gk24.pl/wyscig-po-darmowe-zakupy-w-koszalinskim-lidlu-zobacz-zdjecia-i-film/ar/4421505

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jak na rok 2010, świetny pomysł na konkurs, do tego film ma dużo wyświetleń. Ciekawa pamiątka :)

**Comment by RonaldinhoTHC** [comment]
dodałem
