### ISSUE TITLE
menelski mundial

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#17]
### Nazwa punktu

menelski mundial

### Lokalizacja zdarzenia

Myszków, ul. Siewierska i Pogodna (50.535460, 19.350010)

### Linki do zdarzenia / filmu

https://youtu.be/vABLBRoaClQ (dokładniej od 2:34)

### Dlaczego ten punkt powinien znaleźć się na mapie?

Porządna ilość wyświetleń i niepowtarzalny klimat. Niestety dom głównego bohatera już nie istnieje, jednak wystarczy cofnąć się w czasie przy użyciu Street View.

**Comment by RonaldinhoTHC** [comment]
karek nie rozkręcaj sie tak XD a tak serio to dzięki
