### ISSUE TITLE
Pijany człowiek bije się z niedźwiedziem

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#171]
### Nazwa punktu

Pijany człowiek bije się z niedźwiedziem

### Lokalizacja zdarzenia

52°15'11.3"N 21°01'48.5"E

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=V2sy_UNB9sY

### Dlaczego ten punkt powinien znaleźć się na mapie?

Prawie 1m wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
