### ISSUE TITLE
Gdańska Policja przed Hiltonem "w akcji"

### ISSUE THREAD

**Issue by PiotrDabrowskey** [polskie-mapy/data#172]
### Nazwa punktu

Gdańska Policja przed Hiltonem "w akcji"

### Lokalizacja zdarzenia

54.353310, 18.658105

### Linki do zdarzenia / filmu

https://youtu.be/VsZiUYUwB3I

Dodatkowa weryfikacja lokalizacji: https://maps.app.goo.gl/zMwAJAfcpaZhsoBt5

### Proponowana ikona

https://fontawesome.com/icons/van-shuttle?f=classic&s=solid

### Proponowany kolor

#033dfc

### Dlaczego ten punkt powinien znaleźć się na mapie?

1.5M wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
