### ISSUE TITLE
Pies GPS

### ISSUE THREAD

**Issue by Daeelzis** [polskie-mapy/data#173]
### Nazwa punktu

Lokalizacja teledysku piosenki "Pies GPS"

### Lokalizacja zdarzenia

52°47'47.9"N 18°15'30.7"E | teatr i rynek w Inowrocławiu

### Linki do zdarzenia / filmu

https://youtu.be/JFCBWQc06D0?si=zJV_ayYUTWBBT9em

### Proponowana ikona

https://fontawesome.com/icons/music?f=classic&s=solid

### Proponowany kolor

#58ed80

### Dlaczego ten punkt powinien znaleźć się na mapie?

Znana piosenka (2,7 mln wyświetleń)

**Comment by RonaldinhoTHC** [comment]
może nie XD
