### ISSUE TITLE
Wroniecka 9 

### ISSUE THREAD

**Issue by Villionic** [polskie-mapy/data#174]
### Nazwa punktu

Byłe mieszkanie Michała Woźnickiego

### Lokalizacja zdarzenia

ul. Wroniecka 9, 61-763 Poznań

### Linki do zdarzenia / filmu

https://youtu.be/BsU6kD6gAT8
https://youtu.be/0aQnICus-Rg
https://youtu.be/JXeS9tp87iw

### Proponowana ikona

https://fontawesome.com/icons/cross?f=classic&s=solid

### Proponowany kolor

#000000

### Dlaczego ten punkt powinien znaleźć się na mapie?

Do Września 2022 r. miejsce spotkań sekty Michała Woźnickiego i wielu afer z nią związanych

**Comment by RonaldinhoTHC** [comment]
uniwersum wronieckiej 9 sie chwali dodałem
