### ISSUE TITLE
Nakurwiam węgoża

### ISSUE THREAD

**Issue by Togwass** [polskie-mapy/data#176]
### Nazwa punktu

Nakurwiam węgoża.

### Lokalizacja zdarzenia

Obrońców Pokoju 19C/28, Pruszcz Gdański, 83-000

### Linki do zdarzenia / filmu

https://youtu.be/NvIMu67s8Qs?si=PJO2viQ1YhCOtuhb

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jest to znane nagranie, o którym mówił sam ZEBO. Pozostała twórczość autora przyniosła mu dużą sławę na arenie polskiego YouTube i forów internetowych.

**Comment by RonaldinhoTHC** [comment]
trąci strasznie stalkowaniem, fajna propozycja ale lepiej nie dodawać
