### ISSUE TITLE
Techno w szkole 

### ISSUE THREAD

**Issue by Bruniassty** [polskie-mapy/data#177]
### Nazwa punktu

Techno w szkole

### Lokalizacja zdarzenia

Zespół Szkół Zawodowych nr 2 im. Powstańców Warszawy ul. gen, Generała Kazimierza Sosnkowskiego 43, 05-300 Mińsk Mazowiecki

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=nTmk5yxO2jU

### Dlaczego ten punkt powinien znaleźć się na mapie?

Cytując autorów: 
"Tak się bawimy ze szkolnym zespołem Avista grając jeden, z najbardziej zanych motywów muzyki techno dance w Polsce, Dj Bazz- Andre & Michael znane również jako Dj Hazel Weź-Pigułkę! Jedziemy!!! :D Pozdrawiamy Mechanik Mińsk Mazowiecki! :D"
Film ma prawie 1 milion wyświetleń.

**Comment by RonaldinhoTHC** [comment]
dodałem
