### ISSUE TITLE
Hemoglobina taka sytuacja 

### ISSUE THREAD

**Issue by DawidFulczynski** [polskie-mapy/data#178]
### Nazwa punktu

Hemoglobina taka sytuacja 

### Lokalizacja zdarzenia

Rynek, Ostrów Wielkopolski 

### Linki do zdarzenia / filmu

https://m.youtube.com/watch?v=IuUaAdlbqV4

### Dlaczego ten punkt powinien znaleźć się na mapie?

Znany mem, wywiad

**Comment by RonaldinhoTHC** [comment]
już jest na mapie
