### ISSUE TITLE
Prawdziwe Psy - odc. 1, pościg Trasą Łazienkowską

### ISSUE THREAD

**Issue by wodny** [polskie-mapy/data#180]
### Nazwa punktu

Prawdziwe Psy - odc. 1, pościg Trasą Łazienkowską

### Lokalizacja zdarzenia

52.22539, 21.04925

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=PhTezX34qXI
https://vod.tvp.pl/seriale,18/prawdziwe-psy-odcinki,1239957/odcinek-1,S01E01,1239960

### Dlaczego ten punkt powinien znaleźć się na mapie?

Program Prawdziwe Psy był popularny i wydaje mi się, że jest pamiętany m.in. z powodu tego fragmentu, choć przede wszystkim z powodu Sławka i Edka.

**Comment by RonaldinhoTHC** [comment]
Sławek i Edek jest kultowy ale ten pościg to raczej nie, nie mniej ciekawy pomysł na punkt
