### ISSUE TITLE
Sklep [Pieniądze to nie wszystko]

### ISSUE THREAD

**Issue by RogerOne101** [polskie-mapy/data#181]
### Nazwa punktu

Sklep [Pieniądze to nie wszystko]

### Lokalizacja zdarzenia

52.02583230749178, 21.193595236182528

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=6Q63h_YByRA&t=5564s

### Dlaczego ten punkt powinien znaleźć się na mapie?

bo to miejsce z fajnego filmu :)

**Comment by RonaldinhoTHC** [comment]
dodałem
