### ISSUE TITLE
Knychówek niedaleko Korczewa kręcono tam film "Gwiazdy poranne" z 1979

### ISSUE THREAD

**Issue by MS-Alex-go** [polskie-mapy/data#182]
### Nazwa punktu

"Gwiazdy poranne" z 1979

### Lokalizacja zdarzenia

Knychówek pomiędzy Bartkowem a Korczewem (mazowieckie)

### Linki do zdarzenia / filmu

https://www.filmweb.pl/film/Gwiazdy+poranne-1979-5980

### Proponowana ikona

film

### Dlaczego ten punkt powinien znaleźć się na mapie?

Tam kręcono film (w kościele parafialny, na cmentarzu parafialnym i w jednym z domów (już go nie ma :( )

**Comment by RonaldinhoTHC** [comment]
dodałem
