### ISSUE TITLE
Zamach na Jana Pawła 2

### ISSUE THREAD

**Issue by orlvvs** [polskie-mapy/data#183]
### Nazwa punktu

Zamach na Jana Pawła II

### Lokalizacja zdarzenia

Ostrów, powiat ropczycko-sędziszowski, teren Misterium Fatimskiego

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=IKeoaSHNpiI

### Proponowana ikona

Cross

### Dlaczego ten punkt powinien znaleźć się na mapie?

Popularny film w internecie, przewijający się często nie tylko na Youtubie

**Comment by RonaldinhoTHC** [comment]
dodałem XD co za chore gówno
