### ISSUE TITLE
Zestaw LEGO rynek w Nysie

### ISSUE THREAD

**Issue by WYDUA** [polskie-mapy/data#184]
### Nazwa punktu

Rynek

### Lokalizacja zdarzenia

Woj. Opolskie Rynek miasta Nysa

### Linki do zdarzenia / filmu

![comment_1662044980zOPVa54YjLjFZaZjAob50E](https://github.com/user-attachments/assets/6b66c2d2-5b44-4d2c-ae56-e68d4982af3c)

### Proponowany kolor

Szary

### Dlaczego ten punkt powinien znaleźć się na mapie?

Znany mem krytykujący polską architekturę miejską.

**Comment by RonaldinhoTHC** [comment]
śmieszny pomysł ale mem obrazkowy to nie filmik
