### ISSUE TITLE
[nowy punkt] Matka Boska elektryczno gazowa [Tarnów]

### ISSUE THREAD

**Issue by Wujek280** [polskie-mapy/data#185]
### Nazwa punktu

Matka Boska Elektryczno Gazowa

### Lokalizacja zdarzenia

Tarnów, ul Nowy Świat 43

### Linki do zdarzenia / filmu

https://www.google.com/maps/@50.0166321,20.982823,3a,75y,102.31h,75.74t/data=!3m7!1e1!3m5!1sXKT5D90AjL7mwefV0GtJdw!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D14.258270363073109%26panoid%3DXKT5D90AjL7mwefV0GtJdw%26yaw%3D102.30748722158086!7i16384!8i8192?coh=205410&entry=ttu

https://www.temi.pl/tarnow/matka-boska-elektryczno-gazowa-w-tarnowie

### Proponowana ikona

fa-solid fa-cross

### Proponowany kolor

#4287f5

### Dlaczego ten punkt powinien znaleźć się na mapie?

Transformatorów Jana Pawła ci u nas dostatek.

**Comment by RonaldinhoTHC** [comment]
artykuł to nie filmik
