### ISSUE TITLE
Oskar Pam Pam, Akcja pod Jubilatem

### ISSUE THREAD

**Issue by xcrossxface** [polskie-mapy/data#186]
### Nazwa punktu

Oskar Pam Pam atakuje z partyzanta Tadka

### Lokalizacja zdarzenia

https://maps.app.goo.gl/ju7hpS2a79cbEnEz5

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=L1QvHMFSL3w

Oskar Pam Pam vs Boski Tadek

### Dlaczego ten punkt powinien znaleźć się na mapie?

Internetowy krakowski klasyk, klasyk związany z hip-hopem. A fraza "bierz te swoją kurwe Tadzie" weszła w slang 

Link do pełnego filmu:
https://www.youtube.com/watch?v=k_X1ER_IZgE

**Comment by RonaldinhoTHC** [comment]
dodałem
