### ISSUE TITLE
Piszczu feat Dj kebs - Stąd (prod. Sokollo)

### ISSUE THREAD

**Issue by rafalsony** [polskie-mapy/data#189]
### Nazwa punktu

Piszczu feat Dj kebs - Stąd (prod. Sokollo)

### Lokalizacja zdarzenia

https://maps.app.goo.gl/ZNhz9o8N3JEDfxi3A?g_st=ac

### Linki do zdarzenia / filmu

https://youtu.be/zIAZqMIlbgU?si=laLHymkkpr1Wqer7

### Dlaczego ten punkt powinien znaleźć się na mapie?

Powinno pojawić się to na mapie dlatego że to dobry raper z Grudziądza, łatwo wpada w ucho .

**Comment by RonaldinhoTHC** [comment]
dodałem

**Comment by rafalsony** [comment]
Dodałeś do mapy ale nie widze tego na mapie dlaczego?

**Comment by RonaldinhoTHC** [comment]
sry sie zajebałem, nie dodałem jak coś bo wyświtlenia małe

**Comment by rafalsony** [comment]
Jak małe? 2 tys to nie takie małe
