### ISSUE TITLE
Łódź kurwa!

### ISSUE THREAD

**Issue by mareksuma1985** [polskie-mapy/data#193]
### Nazwa punktu

Łódź kurwa!

### Lokalizacja zdarzenia

https://maps.google.com/maps?layer=c&cbll=51.7572478,19.4308539&cbp=12,352,0,0,0

### Linki do zdarzenia / filmu

[Łódź kurwa!](https://www.youtube.com/watch?v=IJ2kvZpJ_BU)

### Proponowana ikona

https://fontawesome.com/icons/train

### Proponowany kolor

#000000

### Dlaczego ten punkt powinien znaleźć się na mapie?

Tutaj została nagrana scena wysiadania na dworcu w Łodzi z filmu [Ajlawju](https://www.filmweb.pl/film/Ajlawju-1999-567) (1999).

**Comment by H0RNY-DR4G0N** [comment]
Film już znajduję się na mapie

**Comment by RonaldinhoTHC** [comment]
jak tu już kolega zauazył już jest na mapie
