### ISSUE TITLE
Nietypowe zachowanie księdza

### ISSUE THREAD

**Issue by FranciszekMaurer** [polskie-mapy/data#194]
### Link do punktu

https://mapainternetow.pl/maps/1/point/456

### Co jest problemem?

niepoprawny opis

### Proponowana poprawka

Link, który jest w lokalizacji - jest nieaktualny (film został usunięty). Link prowadzący do nagrania:
https://www.youtube.com/watch?v=9_iVndsfGyA

(jeśli źle zgłosiłem - przepraszam z góry.)

### Dlaczego powinna ta zmiana nastąpić?

Przypięty link jest nieaktualny.

**Comment by RonaldinhoTHC** [comment]
dodamy działający link, dziękujemy
