### ISSUE TITLE
Poradnik na wheelie

### ISSUE THREAD

**Issue by dragonpl45669** [polskie-mapy/data#195]
### Nazwa punktu

Poradnik na wheelie

### Lokalizacja zdarzenia

50.76895359613712, 19.834367434094645

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=aV-RByNixco

### Dlaczego ten punkt powinien znaleźć się na mapie?

Profesjonalny pokaz wykonania poprawnego wheelie, pomimo nieudanej próby operator kamery tłumaczy dalej

**Comment by RonaldinhoTHC** [comment]
dodałem
