### ISSUE TITLE
Nananana Władysławowo II

### ISSUE THREAD

**Issue by KyleBzPL** [polskie-mapy/data#198]
### Nazwa punktu

Nananana Władysławowo II

### Lokalizacja zdarzenia

54°48'05.4"N 18°24'14.8"E

### Linki do zdarzenia / filmu

https://youtu.be/cCzG2_wB-3I

### Proponowana ikona

fa-solid fa-water

### Proponowany kolor

#4287f5

### Dlaczego ten punkt powinien znaleźć się na mapie?

Człowiek legenda Władysławowo

**Comment by RonaldinhoTHC** [comment]
dodałem
