### ISSUE TITLE
Miota nim jak szatan

### ISSUE THREAD

**Issue by KyleBzPL** [polskie-mapy/data#199]
### Nazwa punktu

Miota nim jak szatan

### Lokalizacja zdarzenia

51°18'14.5"N 19°33'28.2"E

### Linki do zdarzenia / filmu

https://youtu.be/iosFtJs6xbw

### Proponowana ikona

fa-solid fa-car-burst

### Proponowany kolor

#f54242

### Dlaczego ten punkt powinien znaleźć się na mapie?

Miota nim jak szatan.

**Comment by KarekToArek** [comment]
Niezbyt mi pasuje to miejsce. Nie zgadzają się drzewa i zakręt na drodze.

**Comment by H0RNY-DR4G0N** [comment]
Drzewa są akurat bardzo podobne, ciężko mi powiedzieć jak dokładnie biegnie droga na filmie, ale w zaznaczonym miejscu w 2012 stały krzyże na poboczu, więc przynajmniej wiadomo, że jakiś wypadek miał tam miejsce

**Comment by RonaldinhoTHC** [comment]
dodałem
