### ISSUE TITLE
Jan Polak - Gruba pijesz?

### ISSUE THREAD

**Issue by PatrykSzafron** [polskie-mapy/data#2]
### Nazwa punktu

Gruba Pijesz? Awantura w barze!

### Lokalizacja zdarzenia

brak danych

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=kGLLBWzxAm4

### Dlaczego ten punkt powinien znaleźć się na mapie?

bo jest xd

**Comment by RonaldinhoTHC** [comment]
dodany
