### ISSUE TITLE
Pogrzeb kota

### ISSUE THREAD

**Issue by delllta** [polskie-mapy/data#20]
### Link do punktu

https://mapainternetow.pl/maps/1/point/19

### Prawidłowa lokalizacja

https://goo.gl/maps/uiQRLYnfXuiY56aQA

### Źródło potwierdzające prawidłową lokalizację

![image](https://github.com/polskie-mapy/data/assets/136011385/b791deca-a0ae-4afb-9aa6-4dc52ab8312b)

 /\ *przetłumaczone z białoruskiego/ruskiego z komentarzy pod tym filmikiem:* podobno chłopaki z wideo poszli do wojska

https://www.youtube.com/watch?v=zicU7lWyhjU

**Comment by RonaldinhoTHC** [comment]
dziękujemy za pomoc kolego (lub koleżanko) wiele to dla nas znaczy :D

**Comment by delllta** [comment]
cieszę się że mogłam pomóc (っ◔ ᵕ◔)っ
