### ISSUE TITLE
Precz z komuną! Danka z Niebuszewa

### ISSUE THREAD

**Issue by nyaciora** [polskie-mapy/data#200]
### Nazwa punktu

Danka z Niebuszewa

### Lokalizacja zdarzenia

Szczecin, Niebuszewo targowisko Manhattan i pętla Kołłątaja

### Linki do zdarzenia / filmu

https://youtu.be/1bFaWcQ7ztM?si=4POiHZ4m-CGpSGcj
https://www.youtube.com/watch?v=OOkkAZL7xVc

### Proponowana ikona

https://fontawesome.com/icons/volume-high?f=classic&s=solid

### Proponowany kolor

#3874d6

### Dlaczego ten punkt powinien znaleźć się na mapie?

Szczecin pomimo że jest jednym z większym miast jest często pomijane, nawet w kwestii memów... filmik z danką nie ma wielomilionowych odsłon ale uważam że zasługuję na znalezienie się na mapie memów. Nawet Bądźmypoważni o nim w swoim filmosie _Historia Memów - SZCZECIN_. Wiadomka że on sam jest lokalsem zresztą tak jak ja ale nic dziwnego wspominać o lokalnych memach, choć filmik z Danką przekroczył milion więc aż tak niszowym materiałem nie jest.. Choć danka ma już trochę lat czemu by jej nie dodać? Myślałam też nad zgłoszeniem Balbiny bo porównując jest to świeższy temat ale ona robiła afery w wielu miejscach a Danka łączy się głównie z tą konkretną lokalizacją. 
Odpowiadając jasno na pytanie, uważam że punkt ten powinien się znaleźć na mapie memów z racji że na to zasługuję, z uwagi na staż, długość ponieważ nie jest za długi ani za krótki, przekroczenie miliona wyświetleń co świadczyć może o jego rozpoznawalności, klasyczna chujowa jakość kamery i co najważniejsze tą całą memiczność. Ciekawostka, pomimo że pierwszy film z nią został zamieszczony ponad dekadę temu to na facebooku miała swój fanpage który ostatni raz był aktywny w 2020.
![obraz_2024-09-23_172525858](https://github.com/user-attachments/assets/7850402c-4638-42af-b988-f15199677e27)
![obraz_2024-09-23_173112964](https://github.com/user-attachments/assets/b10dd4f1-842c-4206-8673-9e149b8a5988)

**Comment by RonaldinhoTHC** [comment]
dodałęm
