### ISSUE TITLE
Postawił płot na środku drogi

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#202]
### Nazwa punktu

Postawił płot na środku drogi

### Lokalizacja zdarzenia

ul. Wydmowa, Łódź (51.797675, 19.523225)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=yKFyAuXfJfk

### Dlaczego ten punkt powinien znaleźć się na mapie?

Absurd sytuacji i ponad milion wyświetleń.

**Comment by RonaldinhoTHC** [comment]
dodałem
