### ISSUE TITLE
Kurwa, bo Ci jebnę

### ISSUE THREAD

**Issue by RadoslawNagiel** [polskie-mapy/data#206]
### Nazwa punktu

Kurwa, bo Ci jebnę

### Lokalizacja zdarzenia

Wenecja,  45°26'20.4"N 12°19'10.5"E

### Linki do zdarzenia / filmu

https://youtu.be/HLttZPe0ivs

### Dlaczego ten punkt powinien znaleźć się na mapie?

Zabawna sytuacja. Apsik.

**Comment by H0RNY-DR4G0N** [comment]
Legenda, musi być

**Comment by RonaldinhoTHC** [comment]
świetne, dodałem już
