### ISSUE TITLE
Acodin masters

### ISSUE THREAD

**Issue by Kasjer19** [polskie-mapy/data#207]
### Nazwa punktu

Acodin masters

### Lokalizacja zdarzenia

Lublin Orkana

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=csUpIT5N5rA

### Dlaczego ten punkt powinien znaleźć się na mapie?

O dwóch co przedawkowali acodin

**Comment by RonaldinhoTHC** [comment]
a dokładniejszej lokalizacji nie znasz? Bo chętnie bym dodał

**Comment by Kasjer19** [comment]
Teorytycznie to najdokładniejsza lokalizacja jest tu  maps.app.goo.gl https://maps.app.goo.gl/Tizt9M2DL9f2vxgF9   Teraz stoją tam budynki Luxmedu i inne pierdoły.   Kiedyś tam były krzaki i ogólne pustkowie   PS: Mój znajomy się znał z tymi dwoma, i prawdopodobnie jego brat cioteczny ich nagrywał. Fajnie by było jakby się to znalazło na tej mapie xD 
     
      
       
        Dnia 12 listopada 2024 18:45 RonaldinhoTHC ***@***.***&gt; napisał(a):
       
    
       
         
 a dokładniejszej lokalizacji nie znasz? Bo chętnie bym dodał

**Comment by RonaldinhoTHC** [comment]
dodałem
