### ISSUE TITLE
"Idiota i znak" poprawne umiejscowienie w Warce 

### ISSUE THREAD

**Issue by AnalnyMenel** [polskie-mapy/data#21]
### Link do punktu

https://mapainternetow.pl/maps/1/point/66

### Prawidłowa lokalizacja

https://www.google.com/maps/place/J%C3%B3zefa+Manczarskiego+2,+05-660+Warka/@51.7816096,21.1939845,21z/data=!4m6!3m5!1s0x4718e7387d57d807:0x20a0eef74a3a6f6e!8m2!3d51.7815999!4d21.1940231!16s%2Fg%2F11h463t31w?hl=pl-PL&entry=ttu

### Źródło potwierdzające prawidłową lokalizację

![Przechwytywanie2](https://github.com/polskie-mapy/data/assets/141257020/e3d653a9-f890-4ba6-8e10-bf470a4bd246)
Źródło: https://www.youtube.com/watch?v=EH5rrocv6sI&ab_channel=ZdartyMazak
![Przechwytywanie](https://github.com/polskie-mapy/data/assets/141257020/78528fa2-46ac-4359-aa1c-2b59538d1fff)
Źródło: Google maps, linko do pinezki podany wcześniej
Analiza porównawcza wykazała że miejsce w którym doszło do pojedynku ze znakiem ograniczenia prędkości znajduje się w innym miejscu Warki niż przewidywali naukowcy i wskazywały mapy.

**Comment by RonaldinhoTHC** [comment]
dziękuje w imieniu swoim oraz osób zaangażowanych w projekt mapainternetów.pl
