### ISSUE TITLE
Pomocy, dzwonię z grobu

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#23]
### Nazwa punktu

Pomocy, dzwonię z grobu

### Lokalizacja zdarzenia

Cmentarz Parafialny Św. Barbary, Chorzów (50.304625, 18.946166)

### Linki do zdarzenia / filmu

https://youtu.be/5RCsLUK6wCY

### Dlaczego ten punkt powinien znaleźć się na mapie?

Absurd tej sytuacji i fakt, że dzwoniący trzymał telefon w skarpetce. Po prostu legenda.

**Comment by RonaldinhoTHC** [comment]
dodałem dzięki wielkie od ekipy mapy internetów ;)
