### ISSUE TITLE
Nie potrzebujemy cię w naszym składzie

### ISSUE THREAD

**Issue by vvISDvv** [polskie-mapy/data#28]
### Nazwa punktu

Nie potrzebujemy cię w naszym składzie

### Lokalizacja zdarzenia

51.129327, 16.489255

### Linki do zdarzenia / filmu

https://youtu.be/4UWyL3gxd_o?si=LFvcYVA8-E6FvKUs

### Dlaczego ten punkt powinien znaleźć się na mapie?

Śmieszna wiadomość wysłana do kolegi, który nie przyszedł pograć z chłopakami w piłkę na boisko we Wrocisławicach

**Comment by RonaldinhoTHC** [comment]
filmik jest już na mapie ale zmienie nazwe w sumie
