### ISSUE TITLE
Ponure Radomsko

### ISSUE THREAD

**Issue by gruby070** [polskie-mapy/data#3]
### Nazwa punktu

Ponure Radomsko

### Lokalizacja zdarzenia

https://goo.gl/maps/phxWFhY1QJdfRYs2A

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=hbuR7ahmPas

### Dlaczego ten punkt powinien znaleźć się na mapie?

klasyk wywiadów telewizyjnych

**Comment by cvgore** [comment]
Punkt dodany, dzięki wielkie za propozycje :P

https://mapainternetow.pl/maps/1/point/442
