### ISSUE TITLE
RONDO JEST JEGO

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#31]
### Link do punktu

https://mapainternetow.pl/maps/1/point/462

### Co jest problemem?

niepoprawna ikona

### Proponowana poprawka

Pinezka nie reaguje na klinięcia
Można by też przesunąć nieco lokację na:
54°07'20.2"N 17°58'53.1"E

### Dlaczego powinna ta zmiana nastąpić?

Ikona nie reaguje na kliknięcie przez co mem jest nie do zobaczenia
Można też przy okazji przesunąć ją bliżej faktycznego miejsca zderzenia przy wjeździe z ulicy Wojska Polskiego na rondo

**Comment by RonaldinhoTHC** [comment]
już działa dzięki
