### ISSUE TITLE
Deo dobrze mówić po polsku

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#35]
### Nazwa punktu

Deo dobrze mówić po polsku

### Lokalizacja zdarzenia

Zanzibar, Tanzania

### Linki do zdarzenia / filmu

https://youtu.be/uh27dYTwsK8

### Dlaczego ten punkt powinien znaleźć się na mapie?

Ma sporo wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem aczkolwiek wolałbym znaleźć dokładną lokację. zakładam że jest to w jakiejś szkole albo knajpie w stolicy ale pewności nie mam
