### ISSUE TITLE
rozbite Mi-24 w Afganistanie

### ISSUE THREAD

**Issue by vvISDvv** [polskie-mapy/data#38]
### Nazwa punktu

rozbite Mi-24 w Afganistanie

### Lokalizacja zdarzenia

Afganistan (dokładniejsza lokacja nieznana)

### Linki do zdarzenia / filmu

https://youtu.be/4B3KkL7_J34?si=dwBxpiZ_9kshuPwQ

### Dlaczego ten punkt powinien znaleźć się na mapie?

ekwiwalent "kto kierowcą kurwa jest", ale ze wszystkich miejsc w Afganistanie xDDDD

**Comment by H0RNY-DR4G0N** [comment]
Według materiałów prasowych miało to miejsce w okolicach miasta Ghazni, niedaleko bazy naszych

**Comment by RonaldinhoTHC** [comment]
nawet na wikipedii jest o tym wspomniane: https://en.wikipedia.org/wiki/List_of_aviation_accidents_and_incidents_in_the_war_in_Afghanistan
baza Warrior w Ghazni to 100% pewniak
