### ISSUE TITLE
Tico w sklepie

### ISSUE THREAD

**Issue by daszek0** [polskie-mapy/data#4]
### Link do punktu

https://mapainternetow.pl/maps/1/point/101

### Prawidłowa lokalizacja

-

### Źródło potwierdzające prawidłową lokalizację

Niestety nie wiem, gdzie ten film został nagrany, ale na pewno nie jest to Tesco na Karwinach, ponieważ ono wygląda (wyglądało) inaczej.

**Comment by RonaldinhoTHC** [comment]
poprawiona
