### ISSUE TITLE
Chcesz w pape

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#40]
### Nazwa punktu

Chcesz w pape

### Lokalizacja zdarzenia

52.866477,18.275092, Ściborze

### Linki do zdarzenia / filmu

https://youtu.be/_qCjcUCUAGA?si=f-Wjk2p9rwlwPWmz

### Dlaczego ten punkt powinien znaleźć się na mapie?

Kolejne wideo o menelach
No i double kill w 3 minucie

**Comment by RonaldinhoTHC** [comment]
dodałem
