### ISSUE TITLE
Quasimodo 

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#41]
### Nazwa punktu

Quasimodo 

### Lokalizacja zdarzenia

51.121153,15.912254, Złotoryja

### Linki do zdarzenia / filmu

https://youtu.be/cnBH987gy4I?si=lCOGyhMC1Q99RhQO

### Proponowana ikona

f0f3

### Dlaczego ten punkt powinien znaleźć się na mapie?

0,5mln wyświetleń i całkiem zabawny film z menelem

**Comment by RonaldinhoTHC** [comment]
zajebiste! dodaje af kors
