### ISSUE TITLE
Chodź szogunie

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#42]
### Nazwa punktu

Chodź szogunie

### Lokalizacja zdarzenia

35°40'35.7"N 139°44'40.6"E

### Linki do zdarzenia / filmu

https://youtu.be/XcMkAX99kaA

### Dlaczego ten punkt powinien znaleźć się na mapie?

Słynna wypowiedź byłego prezydenta, która dała początek wielu memom i przeróbkom
Inne, wyedytowane wideo ma dużo więcej wyświetleń, ale wolałbym tu widzieć czystą wersję

**Comment by RonaldinhoTHC** [comment]
dodano
