### ISSUE TITLE
Piston i Romek z flacho

### ISSUE THREAD

**Issue by sebixel2137** [polskie-mapy/data#43]
### Nazwa punktu

Piston i Romek z flacho

### Lokalizacja zdarzenia

50°57'55.1"N 23°44'48.3"E

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=VArNmziTPHc

### Dlaczego ten punkt powinien znaleźć się na mapie?

jeden z kilku klasyków związanych z ekipą Pistona (prawie 3 mln wyświetleń)

**Comment by RonaldinhoTHC** [comment]
dodano
