### ISSUE TITLE
rap o Międzyrzecu Podlaskim 

### ISSUE THREAD

**Issue by vvISDvv** [polskie-mapy/data#44]
### Nazwa punktu

rap o Międzyrzecu Podlaskim 

### Lokalizacja zdarzenia

jak sama nazwa wskazuje - różne ujęcia w różnych częściach miasta

### Linki do zdarzenia / filmu

https://youtu.be/zPR49fybN-w?si=8RM8kPPqvQJas8Pi

### Dlaczego ten punkt powinien znaleźć się na mapie?

potężny stary teledysk z dobrym oldschoolowym flowem 
Międzyrec Podlaski
tu tylko wrony zawracają 
;))

**Comment by RonaldinhoTHC** [comment]
mała ilość wyświetleń ale piosenka jest giga koks
