### ISSUE TITLE
JAZDA NA KIBLU

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#45]
### Nazwa punktu

JAZDA NA KIBLU

### Lokalizacja zdarzenia

Dokładna lokalizacja nieznana, prawdopodobnie wioska w okolicach Rabki-Zdroju, sugerowane miejsce zdarzenia: Spytkowice

### Linki do zdarzenia / filmu

https://youtu.be/_9wto0zbdY4

### Dlaczego ten punkt powinien znaleźć się na mapie?

Film legendarny, choć ustalenie dokładnej lokalizacji niestety będzie wymagać interwencji lokalsa

**Comment by RonaldinhoTHC** [comment]
na razie zamykam póki nie wieadomo dokładnej lokalizacji ale propozycja kozacka. Szykałem info na temat miejsca ale na razie brak danych
