### ISSUE TITLE
Hoduje gołębie

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#46]
### Nazwa punktu

Hodowla gołębi w Czemiernikach

### Lokalizacja zdarzenia

51°40'14.9"N 22°38'35.8"E

### Linki do zdarzenia / filmu

https://youtu.be/vIifcpeUCJM

### Dlaczego ten punkt powinien znaleźć się na mapie?

Piosenka o gołębiach

**Comment by RonaldinhoTHC** [comment]
trochę za mało wyświetleń ale ma potencjał

**Comment by H0RNY-DR4G0N** [comment]
> trochę za mało wyświetleń ale ma potencjał

Teraz już ma ponad 100k wyświetleń
