### ISSUE TITLE
Oldskulowa babcia bije po głowie zalanego w trupa denata!!!

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#48]
### Nazwa punktu

Oldskulowa babcia bije po głowie zalanego w trupa denata!!!

### Lokalizacja zdarzenia

51°29'19.4"N 21°30'32.0"E

### Linki do zdarzenia / filmu

https://youtu.be/1B2rAr8PMJ0

### Dlaczego ten punkt powinien znaleźć się na mapie?

Ponad 1,5kk wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
