### ISSUE TITLE
Gumolit

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#49]
### Nazwa punktu

Gumolit

### Lokalizacja zdarzenia

Lipno, kujawsko-pomorskie

### Linki do zdarzenia / filmu

https://youtu.be/ghwq8opMg7A
https://youtu.be/tzsT1o4zpR0 - gumolit część 2, drugi film z udziałem tych samych bohaterów

### Dlaczego ten punkt powinien znaleźć się na mapie?

Klasyk z 4,5mln wyświetleń

**Comment by RonaldinhoTHC** [comment]
potrzebna dokładniejsza lokalizacja, ulica chociaż
