### ISSUE TITLE
Zderzenie z jeleniem w centrum Bielska-Białej

### ISSUE THREAD

**Issue by vesiakos** [polskie-mapy/data#5]
### Nazwa punktu

Zderzenie z jeleniem w centrum Bielska-Białej

### Lokalizacja zdarzenia

https://www.google.pl/maps/@49.8157286,19.0443929,3a,75y,273.5h,59.4t/data=!3m6!1e1!3m4!1shRBqjyfm6kmyAPnL_RnKmg!2e0!7i16384!8i8192

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=lbEqmnVmm28

### Proponowana ikona

car-burst

### Proponowany kolor

#b6801c

### Dlaczego ten punkt powinien znaleźć się na mapie?

Klasyk bielska białej XD

**Comment by cvgore** [comment]
Punkt dodany, dzięki wielkie za propozycje :P

https://mapainternetow.pl/maps/1/point/441
