### ISSUE TITLE
Kilka słów o rasizmie i cz****ch

### ISSUE THREAD

**Issue by vvISDvv** [polskie-mapy/data#50]
### Nazwa punktu

rasistowska radna

### Lokalizacja zdarzenia

świetlica wiejska, Bierkowo, gmia Słupsk

### Linki do zdarzenia / filmu

https://youtu.be/f_bqu6JOKZo?si=fsAQjXN30iMCub5o

### Dlaczego ten punkt powinien znaleźć się na mapie?

totalny brak zrozumienia mema i kolejna śmieszna wpadka w internecie xD

**Comment by KarekToArek** [comment]
Nie świetlica wiejska, ale sala gimnastyczna szkoły podstawowej [54.476750, 16.929722]

**Comment by RonaldinhoTHC** [comment]
dodałem, dzień bez słowa na cz
