### ISSUE TITLE
Tak średnio bym powiedział bo jedyne co wyniosłem z tego egzaminu to wodę

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#51]
### Nazwa punktu

Tak średnio bym powiedział bo jedyne co wyniosłem z tego egzaminu to wodę

### Lokalizacja zdarzenia

SP nr 1 w Łomży (53.167071, 22.069839)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=pW1sy0bnEW0

### Dlaczego ten punkt powinien znaleźć się na mapie?

3,4 mln wyświetleń, legendarny mem wśród piszących egzamin ósmoklasisty

**Comment by RonaldinhoTHC** [comment]
dodałem
