### ISSUE TITLE
W tym roku to nawet wody nie wyniosłem

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#52]
### Nazwa punktu

W tym roku to nawet wody nie wyniosłem

### Lokalizacja zdarzenia

Zespół Szkół Ekonomicznych i Ogólnokształcących nr 6 w Łomży (53.1743980, 22.0742377)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=XffF4RibmeY

### Dlaczego ten punkt powinien znaleźć się na mapie?

1,5 mln wyświetleń, kontynuacja klasowego mema

**Comment by RonaldinhoTHC** [comment]
dodałem piękna kontynuacja
