### ISSUE TITLE
Rychu w zielonej górze

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#53]
### Nazwa punktu

Rychu w zielonej górze

### Lokalizacja zdarzenia

parking przy stadionie, ul. Sulechowska, Zielona Góra, 51.956198, 15.527192 (źródło: https://zielonagora.dlastudenta.pl/muzyka/artykul/rap-gra-ii-na-winobraniu-2009,41879.html)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=lqaghAf7sd8

### Dlaczego ten punkt powinien znaleźć się na mapie?

140k wyświetleń, ważniejsze wydarzenie w polskim rapie, Peja zwyzywał małolata ze sceny

**Comment by RonaldinhoTHC** [comment]
dodałem
