### ISSUE TITLE
Nie wezme metala na impreze

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#54]
### Nazwa punktu

Nie wezme metala na impreze

### Lokalizacja zdarzenia

51°06'27.0"N 17°01'31.6"E, klub we Wrocku

### Linki do zdarzenia / filmu

https://youtu.be/WRnVD88NilM

### Dlaczego ten punkt powinien znaleźć się na mapie?

Nabzdyngolony Kudłaty z klubie z 2mln wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
