### ISSUE TITLE
POLSKA-LUXEMBURG

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#56]
### Nazwa punktu

POLSKA-LUXEMBURG

### Lokalizacja zdarzenia

Park miejski w Przasnyszu, 53.021806, 20.879238 (on się w paru miejscach pojawiał, ale tam najczęściej)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=DccDDcQ9pEg

### Dlaczego ten punkt powinien znaleźć się na mapie?

370k wyświetleń, rapowanie hymnu, po prostu dzieło sztuki

**Comment by RonaldinhoTHC** [comment]
dodane piękny patriotyczny utwór
