### ISSUE TITLE
pyrek vs nunek walka o papierosy

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#57]
### Nazwa punktu

pyrek vs nunek walka o papierosy

### Lokalizacja zdarzenia

49°48'42.1"N 19°02'04.6"E

### Linki do zdarzenia / filmu

https://youtu.be/Xoqwo8XADfw

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jakby to było normalnie nagrywane to byłby to najlepszy epizod Trudnych Spraw

**Comment by RonaldinhoTHC** [comment]
dodałem
