### ISSUE TITLE
ALE 2 ZŁ BĘDZIESZ MIAŁ

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#58]
### Nazwa punktu

ALE 2 ZŁ BĘDZIESZ MIAŁ

### Lokalizacja zdarzenia

52.069017, 15.861650

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=RJ7BGY4YHa4

### Dlaczego ten punkt powinien znaleźć się na mapie?

Lubuskie "jestem hardcorem"

**Comment by panak0tta** [comment]
Dworcowa 17 ;) 52.069017, 15.861650

**Comment by H0RNY-DR4G0N** [comment]
Rzeczywiście, nic się nie zmieniło

**Comment by RonaldinhoTHC** [comment]
dodałem dzięki za pomoc byq
