### ISSUE TITLE
Pijany wójt Żelazkowa

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#59]
### Nazwa punktu

Pijany wójt Żelazkowa

### Lokalizacja zdarzenia

Urząd Gminy Żelazków: 51.852785,18.176263

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=zAL_8Pjh8fY

### Dlaczego ten punkt powinien znaleźć się na mapie?

Mąż stanu, wybitny włodarz, mimo miliona promili rusza dzielnie do pracy, niemal 1 mln wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
