### ISSUE TITLE
Aleksander Kwaśniewski PIJANY na Ukrainie (z tłumaczeniem)

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#60]
### Nazwa punktu

Aleksander Kwaśniewski PIJANY na Ukrainie (z tłumaczeniem)

### Lokalizacja zdarzenia

Uniwersytet Narodowy im. Tarasa Szewczenko w Kijowie, 50.4422011,30.5040945

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=tHDgHJ2kgj8

### Dlaczego ten punkt powinien znaleźć się na mapie?

jeden z najbardziej memicznych i zapamiętanych wybryków byłego prezydenta, niektóre filmiki z tym zdarzeniem mają ponad 2 mln wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
