### ISSUE TITLE
Maluch EL

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#61]
### Nazwa punktu

Maluch EL

### Lokalizacja zdarzenia

były budynek VIII LO w Poznaniu, ul. Głogowska 92 (52.393064, 16.896564)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=LxHOrHfHnu8

### Dlaczego ten punkt powinien znaleźć się na mapie?

piękna i ambitna próba wniesienia malucha po schodach, 550k wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
