### ISSUE TITLE
Ryszard ty draniu!

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#62]
### Nazwa punktu

Ryszard ty draniu!

### Lokalizacja zdarzenia

Koźniewo Średnie, 52.762188, 20.760648

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=wIVT3yEqVp0

### Dlaczego ten punkt powinien znaleźć się na mapie?

klasyk polskiej telewizji, dramaturgia na wybitnym poziomie, 1,8mln wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
