### ISSUE TITLE
Wjazd na albańską autostradę

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#63]
### Nazwa punktu

Wjazd na albańską autostradę

### Lokalizacja zdarzenia

41.199556, 19.536271

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=CUzM8Ip4mrE

### Dlaczego ten punkt powinien znaleźć się na mapie?

700k wyświetleń, ładne wideo o absurdzie albańskiej infrastruktury drogowej, hitem internetu został późno, ale hit to hit

**Comment by RonaldinhoTHC** [comment]
dodałem
