### ISSUE TITLE
Baba z Sopotu autobus 😱

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#64]
### Nazwa punktu

Baba z Sopotu autobus 😱

### Lokalizacja zdarzenia

Gdańsk, ul. Spacerowa, przystanek Sopocka 01 (54.429878, 18.478382)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=5oYgoFoYZRg

### Dlaczego ten punkt powinien znaleźć się na mapie?

Baba z Sopotu okryła się legendą w trójmiejskiej komunikacji, jej arsenał klątw jest niezwykle obszerny i imponujący, 570k wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
