### ISSUE TITLE
"Pada śnieg" w wykonaniu pracowników POLSKIEJ firmy!

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#65]
### Nazwa punktu

"Pada śnieg" w wykonaniu pracowników POLSKIEJ firmy!

### Lokalizacja zdarzenia

Bytów, ul. Lęborska 31, 54.184738, 17.485858

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=vwAmWvvOQ1E

### Dlaczego ten punkt powinien znaleźć się na mapie?

czyste piekło Januszexu,, jaki kraj, takie "The Office", 340k wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodano, biedni pracownicy XD
