### ISSUE TITLE
Walka pod sklepem

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#66]
### Nazwa punktu

Andrzej, zaskoczył cię

### Lokalizacja zdarzenia

50°39'57.4"N 17°56'58.2"E

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=aO-vM0Xv20M

### Dlaczego ten punkt powinien znaleźć się na mapie?

Porachunki z 700k wyświetleń
Background:
Andrzej, nagrywany przez Marcina, zamierza się rozliczyć za pobicie swojego przyjaciela Arkadiusza ps. Avatar.
Rozerwana koszulka jest skutkiem wspomnianej walki z Arkiem

**Comment by RonaldinhoTHC** [comment]
dodałem

**Comment by H0RNY-DR4G0N** [comment]
Punktu nie ma na mapie
