### ISSUE TITLE
Ale 2 złote będziesz miał: BRAK NAGRANIA

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#67]
### Link do punktu

https://mapainternetow.pl/maps/1/point/482

### Co jest problemem?

niepoprawny opis

### Proponowana poprawka

https://www.youtube.com/watch?v=RJ7BGY4YHa4

### Dlaczego powinna ta zmiana nastąpić?

Brak wideo ze zdarzenia

**Comment by RonaldinhoTHC** [comment]
dodałem linka
