### ISSUE TITLE
Tadeusz Sznuk o braku kobiet w 1 z 10

### ISSUE THREAD

**Issue by vvISDvv** [polskie-mapy/data#69]
### Nazwa punktu

Nie wiem, choć się domyślam

### Lokalizacja zdarzenia

ul. Henryka Raabego 2, 20-080 Lublin - studio TVP3 Lublin

### Linki do zdarzenia / filmu

https://youtu.be/PuJkM5X8BIo?si=32AP6CThB7Dn2-jQ

### Dlaczego ten punkt powinien znaleźć się na mapie?

"nie wiem, choć się domyślam" to w zasadzie już idiom w j. polskim
Pan Tadeusz jak zwykle z klasą B))

**Comment by RonaldinhoTHC** [comment]
dodałem
