### ISSUE TITLE
Kran po Juwenaliach

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#70]
### Nazwa punktu

Kran po Juwenaliach AGH

### Lokalizacja zdarzenia

50°04'09.8"N 19°54'10.6"E

### Linki do zdarzenia / filmu

https://youtu.be/nN0f76-E5U8

### Dlaczego ten punkt powinien znaleźć się na mapie?

800k like

**Comment by RonaldinhoTHC** [comment]
wg komentarzy jest to ds filutek a nie ds akropol ale dodam cię że pomogłeś ;)

**Comment by RonaldinhoTHC** [comment]
dodaned
