### ISSUE TITLE
felgi sie gno

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#71]
### Nazwa punktu

felgi sie gno

### Lokalizacja zdarzenia

53°08'31.5"N 19°16'40.3"E, Wąpielsk, powiat rypiński

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=GHTtW_n5WiU

### Dlaczego ten punkt powinien znaleźć się na mapie?

Drift maluchem, zdemolowana studnia oraz kamerzysta, który omal nie postradał życia

**Comment by H0RNY-DR4G0N** [comment]
Główna yt

**Comment by H0RNY-DR4G0N** [comment]
Miejscowość była w komentarzach, a dokładnej lokalizacji nie jestem pewny, bo to tylko porównanie zdjęcia satelitarnego z filmem

**Comment by RonaldinhoTHC** [comment]
dodałem jak to znalazłeś nie chce wiedzieć XD
