### ISSUE TITLE
Wjechał traktorem do Tesco

### ISSUE THREAD

**Issue by Dominiczeczek** [polskie-mapy/data#72]
### Nazwa punktu

Wjechał traktorem do Tesco

### Lokalizacja zdarzenia

Tesco w Stalowej Woli. Obecnie w tym budynku znajduje się Castorama (ul.Przemysłowa 2B)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=WmLqmIromNM

### Dlaczego ten punkt powinien znaleźć się na mapie?

Bo była to sprawa głośna w całej Polsce, patrz: artykuły Onet, Wprost, RMF24, fakt itp itd
+ chcę wzbogacić ten wspaniały projekt

**Comment by RonaldinhoTHC** [comment]
dodałem
