### ISSUE TITLE
Dyskoteka szkolna

### ISSUE THREAD

**Issue by Aragzit** [polskie-mapy/data#73]
### Nazwa punktu

Dyskoteka szkolna

### Lokalizacja zdarzenia

52°18'07.5"N 16°57'56.6"E

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=EBfDp5rWbM0&ab_channel=dutymale

### Dlaczego ten punkt powinien znaleźć się na mapie?

1kk wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodałem
