### ISSUE TITLE
Cygan z LAMBO [TOP] Gear POLSKA

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#74]
### Nazwa punktu

Cygan z LAMBO [TOP] Gear POLSKA

### Lokalizacja zdarzenia

ul. Dojazdowa, Włocławek (52.646306, 19.062111)

### Linki do zdarzenia / filmu

https://youtu.be/-DA7lperYAk

### Dlaczego ten punkt powinien znaleźć się na mapie?

Legenda motoryzacji + powrót samochodu w 2023

**Comment by RonaldinhoTHC** [comment]
tobi king dodany
