### ISSUE TITLE
Perfekcyjny wjazd na lawete

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#76]
### Nazwa punktu

Perfekcyjny wjazd na lawete

### Lokalizacja zdarzenia

50°52'19.1"N 16°20'16.3"E

### Linki do zdarzenia / filmu

https://youtu.be/gDhrpkLs57c

### Dlaczego ten punkt powinien znaleźć się na mapie?

Prawie milion wyświetleń

**Comment by RonaldinhoTHC** [comment]
dodane
