### ISSUE TITLE
Maniu - Reklama Netii

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#77]
### Nazwa punktu

Maniu - Reklama Netii

### Lokalizacja zdarzenia

ul. Stanisława Staszica, Złotoryja (51.122950, 15.918910)

### Linki do zdarzenia / filmu

https://youtu.be/BFl9AI2XNoE

### Dlaczego ten punkt powinien znaleźć się na mapie?

Najpopularniejsza reklama dla Netii i (moim skromnym zdaniem) najlepsza.

**Comment by RonaldinhoTHC** [comment]
dodano
