### ISSUE TITLE
zaawansowane gaszenie światła, pałac kultury

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#78]
### Nazwa punktu

zaawansowane gaszenie światła, pałac kultury

### Lokalizacja zdarzenia

plac Piłsudskiego, Warszawa (52.241950, 21.013560)

### Linki do zdarzenia / filmu

https://youtu.be/1SGiw0u5xms

### Dlaczego ten punkt powinien znaleźć się na mapie?

Filmik na poziomie, porządna ilość wyświetleń + znalazł się w legendarnej serii od lukas545

**Comment by RonaldinhoTHC** [comment]
dodałem
