### ISSUE TITLE
Polskie drogi. No co zrobisz? Nic nie zrobisz

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#79]
### Nazwa punktu

Polskie drogi. No co zrobisz? Nic nie zrobisz

### Lokalizacja zdarzenia

skrzyżowanie Swojskiej i Klukowskiej, Warszawa (52.271500, 21.082000)

### Linki do zdarzenia / filmu

https://youtu.be/hoXhA1qTqug

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jeden z najsłynniejszych i legendarnych filmików z polskich dróg.

**Comment by RonaldinhoTHC** [comment]
dodałem
