### ISSUE TITLE
Gościu babkę zapina na wieży

### ISSUE THREAD

**Issue by NeroDidNothing** [polskie-mapy/data#8]
### Link do punktu

https://mapainternetow.pl/maps/1/point/8

### Prawidłowa lokalizacja

NIE WIEM GDZIE ALE W BELGII A NIE W HISZPANI

### Źródło potwierdzające prawidłową lokalizację

W opisie jest że belgijskie miasto, to zawsze jakaś poprawka

**Comment by RonaldinhoTHC** [comment]
punkt jest zaznaczony poprawnie to belgijskie miasto, o którym mówisz, to ta babka co była zapinana na wieży to jest burmistrzem tego miasta a raczej była burmistrzem bo nie żyje
