### ISSUE TITLE
Coś nie coś potrafie... Polski Karateka z Legnicy HIT 2022

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#80]
### Nazwa punktu

Coś nie coś potrafie... Polski Karateka z Legnicy HIT 2022

### Lokalizacja zdarzenia

Legnica, róg ul. Książęcej i ul. Żwirki i Wigury (51.208817, 16.149785)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=jkWbp6I7kzo

### Dlaczego ten punkt powinien znaleźć się na mapie?

1,5 mln wyświetleń, wybitny i przeskromny karateka, reakcje Jaworowicz też memiczne

**Comment by RonaldinhoTHC** [comment]
dodano
