### ISSUE TITLE
Z babcią nie pogadasz...

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#81]
### Nazwa punktu

Z babcią nie pogadasz...

### Lokalizacja zdarzenia

Bielejewo, pow. jarociński (52.009657, 17.380294) (dokładnej lokalizacji wewnątrz wsi niestety nie mam)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=DqP62sxHnXA

### Dlaczego ten punkt powinien znaleźć się na mapie?

6 mln wyświetleń, autor uwiecznił starożytny język, podziw

**Comment by RonaldinhoTHC** [comment]
dodałem, wydaje mi sie że budynki ceglane na dole wsi to dokładna lokacja pewności nie mam ale są to jedyne budynki ceglane w tej wsi
