### ISSUE TITLE
pijana babcia

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#82]
### Nazwa punktu

pijana babcia

### Lokalizacja zdarzenia

Pruszcz Gdański, ul. Chopina (54.261861, 18.639151)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=LzOtEXaaIyI

### Dlaczego ten punkt powinien znaleźć się na mapie?

2,1 mln wyświetleń, poza tym bardzo miła i pozytywna kobieta, promile spożytkowane w najlepszy sposób

**Comment by RonaldinhoTHC** [comment]
dodałem
