### ISSUE TITLE
Stop dopalaczom - spot 1

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#84]
### Nazwa punktu

Stop dopalaczom

### Lokalizacja zdarzenia

Warszawa, zaplecze przy ul. Targowej 65 (52.253215, 21.034880)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=V7MUrxkwJvo

### Dlaczego ten punkt powinien znaleźć się na mapie?

legendarny spot GIS-u z lata 2015, wybitne dialogi, wybitna gra aktorska, ta wersja ma ledwie 200k wyświetleń, ale oryginalna, niestety usunięta, miała kilka razy więcej; napisano na jego temat kilka artykułów i był obiektem przeróbek oraz ogólnopolskiej beki w tamtym czasie

**Comment by RonaldinhoTHC** [comment]
dodałem
