### ISSUE TITLE
Super babcia w super maluchu

### ISSUE THREAD

**Issue by KarekToArek** [polskie-mapy/data#85]
### Nazwa punktu

Super babcia w super maluchu

### Lokalizacja zdarzenia

droga S8, Emilianów (52.444611, 21.253444)

### Linki do zdarzenia / filmu

https://youtu.be/YN8xvDEFGGg

### Dlaczego ten punkt powinien znaleźć się na mapie?

Legendarna super babcia w super maluchu. Nic dodać, nic ująć.

**Comment by RonaldinhoTHC** [comment]
dodałem
