### ISSUE TITLE
Autobus tonie w asfalcie.avi

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#86]
### Nazwa punktu

Autobus tonie w asfalcie.avi

### Lokalizacja zdarzenia

Łódź, róg ul. Wojska Polskiego i ul. Spornej (51.789272, 19.479542)

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=mu4FYaj8ZDM

### Dlaczego ten punkt powinien znaleźć się na mapie?

1,1 mln wyświetleń, zabawna porażka łódzkiego MPK i łódzkich drogowców z warunkami atmosferycznymi

**Comment by RonaldinhoTHC** [comment]
dodałem
