### ISSUE TITLE
Pie*dole, ja dostaję tylko 5000 złoty ku*wa pensji

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#87]
### Nazwa punktu

Pierdole, ja dostaję tylko 5000 złoty kurwa pensji

### Lokalizacja zdarzenia

wieś Grubsko, nowotomyski

### Linki do zdarzenia / filmu

https://youtu.be/zGcECLvuXuk

### Dlaczego ten punkt powinien znaleźć się na mapie?

ponad 700k

**Comment by RonaldinhoTHC** [comment]
zbyt nie dokładne, po za tym lokacja w budynku - unikamy takich ze względu na ryzyko posądzenia o doxing
