### ISSUE TITLE
Korwin hajluje w europarlamencie

### ISSUE THREAD

**Issue by panak0tta** [polskie-mapy/data#88]
### Nazwa punktu

Korwin hajluje w europarlamencie

### Lokalizacja zdarzenia

siedziba Parlamentu Europejskiego, Strasburg, 48.597522, 7.770011

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=_FU--EfPmJ0

### Dlaczego ten punkt powinien znaleźć się na mapie?

najnormalniejsza wypowiedź Korwina, niemal 4 mln wyświetleń, hit nie tylko polskiego, ale i międzynarodowego internetu

**Comment by RonaldinhoTHC** [comment]
.

**Comment by RonaldinhoTHC** [comment]
dodano
