### ISSUE TITLE
pasztet zajebisty

### ISSUE THREAD

**Issue by Kurwicjusz** [polskie-mapy/data#89]
### Nazwa punktu

Zajepasztet

### Lokalizacja zdarzenia

Poniatowa, Województwo lubelskie, dokładne miejsce nieznane

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=IR5ISm0_Y5k

### Proponowana ikona

f81f

### Dlaczego ten punkt powinien znaleźć się na mapie?

oryginał ma 5.7mln wyświetleń oraz masę parodii i dziwi mnie to bardzo że niema on jeszcze punktu na mapie

**Comment by RonaldinhoTHC** [comment]
lokacja w budynku, unikamy takich bo mieliśmy z paroma problem że doxujemy ludzi XD, wiem że niedokładna ale jednak wolimy dmuchać na zimne
