### ISSUE TITLE
Cygańskie powstanie - Maszkowice

### ISSUE THREAD

**Issue by JestemZsanoka** [polskie-mapy/data#9]
### Nazwa punktu

Cyganie Maszkowice

### Lokalizacja zdarzenia

Wioska cyganów k. m.  Maszkowice

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=IDRd3ii_Jhc

### Dlaczego ten punkt powinien znaleźć się na mapie?

Duża ilosc wyświetleń.
Jeżeli punkt pojawi sie na mapie, prosze o linka do profilu ig @zaufaj_jestem_inzynierem

**Comment by RonaldinhoTHC** [comment]
dodane
