### ISSUE TITLE
Bombsite A

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#91]
### Nazwa punktu

Bombsite A

### Lokalizacja zdarzenia

52°22'48.8"N 16°54'50.2"E lokacja znaleziona na facebooku studia nagrywającego teledysk

### Linki do zdarzenia / filmu

https://youtu.be/WxevjJBOO0o

### Dlaczego ten punkt powinien znaleźć się na mapie?

Memiczna piosenka z milionami wyświetleń i do tego łatwiejsze do znalezienia niż Pakistańskie Disco

**Comment by RonaldinhoTHC** [comment]
dodałem
