### ISSUE TITLE
Yellow Submarine

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#92]
### Nazwa punktu

Yellow Submarine

### Lokalizacja zdarzenia

50°51'50.0"N 17°27'59.2"E

### Linki do zdarzenia / filmu

https://youtu.be/_Efr6Q0QIYI

### Dlaczego ten punkt powinien znaleźć się na mapie?

Jest to słynny występ JKM na Festiwalu Piosenki Angielskiej w Brzegu

**Comment by RonaldinhoTHC** [comment]
dodaliśmy
