### ISSUE TITLE
Labul wali w gong

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#93]
### Nazwa punktu

Labul pierdolnij w gong

### Lokalizacja zdarzenia

45°59'58.7"N 1°12'50.2"W ,fort Boyard

### Linki do zdarzenia / filmu

https://youtu.be/KoL7PvReu_g

### Dlaczego ten punkt powinien znaleźć się na mapie?

300k wyświetleń na łatwym do wmontowania klipie z polskiego serialu

**Comment by RonaldinhoTHC** [comment]
jestem zdania że to nie na tej mapie raczej na filmowej ale z tym to poczekamy jak będęmiał więcej czasu
