### ISSUE TITLE
Chryzantemy Złociste

### ISSUE THREAD

**Issue by H0RNY-DR4G0N** [polskie-mapy/data#96]
### Nazwa punktu

Chryzantemy Złociste

### Lokalizacja zdarzenia

51°44'46.1"N 19°27'00.2"E

### Linki do zdarzenia / filmu

https://youtu.be/SDFdzLJBH7g

W poszukiwaniach pomógł @vvISDvv

### Dlaczego ten punkt powinien znaleźć się na mapie?

Miejsce nagrania kultowej dla polskiego internetu piosenki

**Comment by RonaldinhoTHC** [comment]
pierwsze pytanie: skąd niby wiecie gdzie piosenka została nagrana? 
drugie pytanie: Macie jakieś źródło tej informacji?
trzecie pytanie: Nie uważacie że będzie dziwne wstawiać na mapke miejsce nagrania piosenki która nie ma nawet teledysku? W takim rozrachunku mógłbym wstawić kilkaset memicznych piosenek i podać adres studia nagraniowego, w którym piosenka została nagrana. Nie przesadzajcie XD

**Comment by H0RNY-DR4G0N** [comment]
Słusznie, słusznie
