### ISSUE TITLE
Baba z Sopotu autobus

### ISSUE THREAD

**Issue by vvISDvv** [polskie-mapy/data#98]
### Nazwa punktu

Opętana baba z Sopotu na przystanku

### Lokalizacja zdarzenia

przystanek autobusowy Sopocka 01, Osowa, Gdańsk

### Linki do zdarzenia / filmu

https://www.youtube.com/watch?v=5oYgoFoYZRg

### Dlaczego ten punkt powinien znaleźć się na mapie?

Opętana baba z Sopotu atakuje ponownie D:

**Comment by H0RNY-DR4G0N** [comment]
Jest już na mapie
